function reset(){	chooseRainEvent(0);}
function button1(){	chooseRainEvent(1);}
function button2(){	chooseRainEvent(2);}
function button3(){	chooseRainEvent(3);}
function button4(){	chooseRainEvent(4);}
function button5(){	chooseRainEvent(5);}
function button6(){	chooseRainEvent(6);}
function button7(){	chooseRainEvent(7);}
function button8(){	chooseRainEvent(8);}
function button9(){	chooseRainEvent(9);}
function button10(){	chooseRainEvent(10);}
function button11(){	chooseRainEvent(11);}
function button12(){	chooseRainEvent(12);}
function button13(){	chooseRainEvent(13);}
function button14(){	chooseRainEvent(14);}
